CREATE TABLE DORM_ROOM (
  DormRoomName VARCHAR(20) NOT NULL,
  NumberOfRoomOccupants INT NOT NULL,
  AvailableSpots INT NOT NULL,
  PRIMARY KEY (DormRoomName)
);

CREATE TABLE COLLEGE_STAFF_ACCOUNT (
  StaffID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  EmailAddress VARCHAR(100) NOT NULL,
  Username VARCHAR(30) NOT NULL,
  PasswordHash VARCHAR(255) NOT NULL,
  PRIMARY KEY (StaffID),
  UNIQUE (Username)
);

CREATE TABLE Administrates (
  DormRoomName VARCHAR(20) NOT NULL,
  StaffID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (DormRoomName, StaffID),
  FOREIGN KEY (DormRoomName) REFERENCES DORM_ROOM(DormRoomName),
  FOREIGN KEY (StaffID) REFERENCES COLLEGE_STAFF_ACCOUNT(StaffID)
);

CREATE TABLE STUDENT_ACCOUNT (
  Phone VARCHAR(15) NOT NULL,
  StudentID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  EmailAddress VARCHAR(100) NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Username VARCHAR(30) NOT NULL,
  PasswordHash VARCHAR(255) NOT NULL,
  DormRoomName VARCHAR(20),
  PRIMARY KEY (StudentID),
  FOREIGN KEY (DormRoomName) REFERENCES DORM_ROOM(DormRoomName),
  UNIQUE (Username),
  CHECK (EmailAddress LIKE '%_@__%.__%')
);

CREATE TABLE HOUSING_APPLICATION (
  ApplicationID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Status ENUM('Submitted', 'Approved', 'Rejected') NOT NULL,
  SubmissionDate DATE NOT NULL,
  StudentID BIGINT UNSIGNED NOT NULL,
  StaffID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (ApplicationID),
  FOREIGN KEY (StudentID) REFERENCES STUDENT_ACCOUNT(StudentID),
  FOREIGN KEY (StaffID) REFERENCES COLLEGE_STAFF_ACCOUNT(StaffID)
);